### ISSUE TITLE
If there is folding at the last line of the file, it removes the whole fold

### ISSUE THREAD

**Issue by spott** [nbouscal/vim-stylish-haskell#1]
this can be fixed by replacing the "normal! Gdd" with "normal! GzoGdd"

**Comment by tene** [comment]
A slightly better fix that doesn't always open the fold on the last line is to change append(0,...) to append(1,...) and change G"_dd to gg"_dd

**Comment by nbouscal** [comment]
In my testing, both the way that it currently is written and with either suggestion, the folded content is not deleted, but the fold (and all folds in the entire file) is removed. I don't know how to preserve the folds, but would be happy to implement a solution if someone can provide one.
