### ISSUE TITLE
Redo is broken after save.

### ISSUE THREAD

**Issue by joecrayne** [nbouscal/vim-stylish-haskell#4]
Without the plugin, the following works:

1. undo an action (key u)
2. save the file (:w)
3. redo the action (key ^r)

With the plugin installed, the last step does not work.  Instead I see "Already at newest change"

**Comment by nbouscal** [comment]
Yeah, I'm aware of this issue but don't know of any way to fix it. Essentially, running stylish-haskell on the file contents puts us into a different branch of vim's undo tree. You should be able to redo by navigating back to the old branch of the undo tree (plugins like Gundo come in handy here).

**Comment by expipiplus1** [comment]
Apparently there is a solution here: https://github.com/fatih/vim-go/issues/40
